### ISSUE TITLE
HGServer does not start due to Magic config error

### ISSUE THREAD

**Issue by isolatorhk** [Helbreath/Helbreath.HGServerConsole#47]
Observed in HGServerConsole log:
(!) MAGIC configuration contents received. Now decoding...
(!!!) CRITICAL ERROR! MAGIC configuration file error - Wrong Data format.
(!!!) STOPPED! MAGIC configuration error.

Replaced with the origin Magic.cfg file and it worked.
Maybe related to "Update Magic.cfg" https://github.com/Helbreath/Helbreath.ServerFiles/commit/507fb32c5de7cf37e915bd74b3872cc07ff82993

**Comment by isolatorhk** [comment]
Origin Magic.cfg  (Worked)
`[MAGIC]		-2																			
		-1	Name	Type	Delay	Duration	Mana	H	V	d1	f1	+	d2	f2	+	[6]	[7]	Int	Cost	Category	Attr
magic	=	0	Magic-Missile	1	0	0	8	1	1	1	8	0	0	0	0	0	0	18	20	1	2
magic	=	1	Heal	2	0	0	15	1	1	2	6	10	0	0	0	0	0	20	20	0	4
magic	=	2	Create-Food	10	0	0	18	1	1	1	0	0	0	0	0	0	0	18	20	0	0
magic	=	3	GM-Kill(3x3)	23	0	0	10	3	3	999	999	999	999	999	999	999	999	10	-1	0	100
magic	=	4	Mass-GM-Kill	21	0	0	10	18	18	999	999	999	999	999	999	999	999	10	-1	0	100
magic	=	10	Energy-Bolt	3	0	0	15	3	3	2	4	1	2	4	1	0	0	24	40	1	2
		10	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	11	Staminar-Drain	5	0	0	14	3	3	4	7	14	2	7	7	0	0	22	40	1	0
magic	=	12	Recall	8	0	0	15	1	1	1	0	0	0	0	0	0	0	20	24	0	0
magic	=	13	Defense-Shield	11	0	60	19	1	1	3	0	0	0	0	0	0	0	26	40	2	0
magic	=	14	Celebrating-Light	2	0	0	20	1	1	0	0	0	0	0	0	0	0	25	80	0	2
magic	=	20	Fire-Ball	3	0	0	27	3	3	2	6	2	2	6	2	0	0	26	100	1	3
		20	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	21	Great-Heal	2	0	0	28	1	1	4	10	20	0	0	0	0	0	28	100	0	0
magic	=	23	Staminar-Recovery	7	0	0	20	3	3	4	8	8	2	6	5	0	0	20	60	0	0
magic	=	24	Protection-From-Arrow	11	0	60	22	1	1	1	0	0	0	0	0	0	0	20	60	2	0
magic	=	25	Hold-Person	12	0	30	24	1	1	1	0	0	0	0	0	0	0	26	100	1	0
magic	=	26	Possession	15	0	0	25	1	1	1	0	0	0	0	0	0	0	26	100	1	0
magic	=	27	Poison	17	0	0	28	1	1	1	15	0	0	0	0	0	0	29	140	1	1
magic	=	28	Great-Staminar-Recov.	7	0	0	45	3	3	4	16	16	2	12	10	0	0	30	160	0	0
magic	=	30	Fire-Strike	3	0	0	36	5	5	2	8	3	2	8	3	0	0	34	200	1	3
		30	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	31	Summon-Creature	9	0	0	35	1	1	1	1	0	0	0	0	0	0	38	200	1	1
magic	=	32	Invisibility	13	0	60	31	1	1	1	0	0	0	0	0	0	0	30	160	1	0
magic	=	33	Protection-From-Magic	11	0	60	35	1	1	2	0	0	0	0	0	0	0	32	170	2	0
magic	=	34	Detect-Invisibility	13	0	0	33	1	1	2	0	0	0	0	0	0	0	30	140	0	0
magic	=	35	Paralyze	12	0	20	35	1	1	2	0	0	0	0	0	0	0	36	200	1	0
magic	=	36	Cure	17	0	0	32	1	1	0	0	0	0	0	0	0	0	35	140	0	1
magic	=	37	Lightning-Arrow	1	0	0	32	1	1	4	5	10	0	0	0	0	0	38	220	1	2
magic	=	38	Tremor	22	0	0	34	3	3	3	4	3	3	4	3	0	0	33	200	1	1
magic	=	40	Fire-Wall	14	0	30	42	5	5	8	0	0	0	0	0	1	1	45	240	1	3
		40	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	41	Fire-Field	14	0	30	48	3	3	8	0	0	0	0	0	1	2	48	280	1	3
magic	=	42	Confuse-Language	16	0	120	40	1	1	1	0	0	0	0	0	0	0	42	260	1	0
magic	=	43	Lightning	1	0	0	44	1	1	4	7	12	0	0	0	0	0	47	340	1	2
magic	=	44	Great-Defense-Shield	11	0	40	45	1	1	4	0	0	0	0	0	0	0	46	300	2	0
magic	=	45	Chill-Wind	23	0	0	48	3	3	2	8	3	2	8	3	5	0	50	400	1	4
magic	=	46	Poison-Cloud	14	0	30	48	3	3	15	0	0	0	0	0	10	2	49	360	1	1
magic	=	47	Triple-Energy-Bolt	3	0	0	40	5	5	2	4	2	3	8	3	0	0	45	340	1	2
magic	=	50	Berserk	18	0	60	57	1	1	1	0	0	0	0	0	0	0	59	440	1	0
		50	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	51	Lightning-Bolt	19	0	0	58	3	3	4	5	18	4	2	6	0	0	58	500	1	2
//magic	=	52	Polymorph	20	0	60	55	1	1	1	0	0	0	0	0	0	0	55	460	1	0
magic	=	53	Mass-Poison	17	0	0	54	1	1	1	40	0	0	0	0	0	0	52	420	1	1
magic	=	54	Spike-Field	14	0	30	56	5	5	8	0	0	0	0	0	9	2	56	460	1	1
magic	=	55	Ice-Storm	14	0	30	58	3	3	0	0	0	0	0	0	8	0	59	-1	1	4
magic	=	56	Mass-Lightning-Arrow	1	0	0	55	1	1	5	6	20	0	0	0	0	0	53	600	1	2
magic	=	57	Ice-Strike	23	0	0	59	5	5	5	6	12	0	0	0	4	0	60	840	1	4
magic	=	60	Energy-Strike	21	0	0	65	5	5	0	0	0	7	6	17	0	0	67	1000	1	2
		60	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	61	Mass-Fire-Strike	3	0	0	80	5	5	7	3	5	8	6	18	0	0	85	-1	1	3
magic	=	62	Confusion	16	0	20	78	3	3	2	0	0	0	0	0	0	0	75	1500	1	0
magic	=	63	Mass-Chill-Wind	23	0	0	90	5	5	6	8	6	6	8	6	10	0	93	1960	1	4
magic	=	64	Earthworm-Strike	25	0	0	80	3	3	7	7	19	7	6	17	0	0	97	2400	1	1
magic	=	65	Absolute-Magic-Protect.	11	0	60	90	1	1	5	0	0	0	0	0	0	0	112	2700	2	0
magic	=	66	Armor-Break	26	0	0	90	3	3	7	6	17	7	6	17	20	0	97	4000	1	1
magic	=	67	Scan	31	0	0	50	1	1	0	0	0	0	0	0	0	0	70	4000	1	1
magic	=	70	Bloody-Shock-Wave	19	0	0	120	3	3	7	8	20	7	4	9	0	0	105	-1	1	2
		70	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	71	Mass-Confusion	16	0	60	125	5	5	2	0	0	0	0	0	0	0	130	3000	1	0
magic	=	72	Mass-Ice-Strike	23	0	0	120	5	5	7	6	17	0	0	0	7	0	133	4200	1	4
magic	=	73	Cloud-Kill	14	0	30	130	5	5	40	0	0	0	0	0	10	2	120	4000	1	1
magic	=	74	Lightning-Strike	21	0	0	90	5	5	0	0	0	8	7	20	0	0	123	7000	1	2
magic	=	75	Ice-Whirlwind	23	0	0	120	3	3	6	6	12	0	0	0	2	0	200	-1	1	4
magic	=	76	Cancellation	28	0	30	120	1	1	1	0	0	0	0	0	0	0	135	-200	1	0
magic	=	77	Illusion-Movement	16	0	30	150	3	3	4	0	0	0	0	0	0	0	160	5600	1	0
magic	=	80	Illusion	16	0	20	143	3	3	3	0	0	0	0	0	0	0	150	5400	1	0
		80	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	81	Meteor-Strike	3	0	0	120	3	3	7	2	11	8	8	18	0	0	169	8000	1	3
magic	=	82	Mass-Magic-Missile	33	0	0	160	3	3	5	2	20	7	7	20	0	0	185	8400	1	2
magic	=	83	Inhibition-Casting	29	0	40	160	1	1	1	0	0	0	0	0	0	0	172	-200	1	0
magic	=	84	Air-Blast	19	0	0	130	3	3	0	0	0	9	9	10	0	0	178	-11	0	2
magic	=	85	Mass-Berkserk	18	0	180	90	1	1	1	0	0	0	0	0	0	0	105	5000	1	0
magic	=	90	Mass-Illusion	16	0	60	200	3	3	3	0	0	0	0	0	0	0	180	7000	1	0
		90	Name	Type	Delay	Duration	Mana	H	V	[0]	[1]	[2]	[3]	[4]	[5]	[6]	[7]	Int	Cost	Category	Attr
magic	=	91	Blizzard	27	0	0	170	5	5	5	3	20	5	8	25	7	0	195	8600	1	4
magic	=	92	Absolute-Protect-Arrow	11	0	60	90	1	1	7	0	0	0	0	0	0	0	100	-1	2	0
magic	=	94	Ressurection	32	0	0	200	1	1	4	10	20	0	0	0	0	0	0	-1	0	0
magic	=	95	Mass-Illusion-Movement	16	0	40	200	3	3	4	0	0	0	0	0	0	0	200	7600	1	0
magic	=	96	Earth-Shock-Wave	30	0	0	180	3	3	5	2	20	7	8	16	0	0	200	-200	1	1
magic	=	97	Greater-Heal	2	0	0	250	1	1	5	12	24	0	0	0	0	0	200	-1	0	0
//magic	=	97	Plague	14	0	30	295	5	5	80	0	0	0	0	0	10	2	170	4000	1	1
magic	=	98	Create-Bounty	10	0	0	18	6	6	1	0	0	0	0	0	0	0	18	-100	0	0
magic	=	99	Absolute-Magic-Protect.	11	0	60	100	1	1	5	0	0	0	0	0	0	0	112	-1	2	0
`

**Comment by pawelsawicz** [comment]
Issue is created https://github.com/Helbreath/Helbreath.ServerFiles/issues/6.

Let's keep conversation there.
