### ISSUE TITLE
False speedhack detection

### ISSUE THREAD

**Issue by isolatorhk** [Helbreath/Helbreath.HGServerConsole#49]
Log:
(-~-HACKING-~-) Speed hacker detected(test) - run-avg(45). BI banned

I see something similar for speed-cast hacking detection.

Investigate and fix the detection.

**Comment by pawelsawicz** [comment]
it was fixed with #42

**Comment by isolatorhk** [comment]
You highered the bar in your fix. e.g. 1200 -> 1000. But in this case my run-avg is 45, making it still considered as a speed hack. I have no idea how it ends up with 45, but I didn't do any speed hack.

**Comment by pawelsawicz** [comment]
yeah I was wondering about removing this completely doesn't make sense with new computers

**Comment by pawelsawicz** [comment]
Ok let's remove this ban bur leave information that somebody it "speed hacking"
