### ISSUE TITLE
Cast of mag cant be interrupted

### ISSUE THREAD

**Issue by pawelsawicz** [Helbreath/Helbreath.HGServerConsole#90]
When Mag is casting a spell, it can't be interrupted by damage.

Please investigate :mag: @X4N1 . Please test interruption for this cases :

- Mag is casting and is hit by a spell
- Mag is casting and is hit by hand
- Mag is casting and is hit by weapon
- Mag is casting and is hit by monster

**Comment by 4LifeX** [comment]
This would be an easy fix, looking into magic casting in both clients and HGServer.

**Comment by pawelsawicz** [comment]
Check this issue with @X4N1 and it is working, I am going to close it.
